Better handling of cache/lock in bash_parallel

diff --git a/bash_parallel b/bash_parallel
--- a/bash_parallel
+++ b/bash_parallel
@@ -2,19 +2,19 @@
 
 ### Helpers begin
 set -o noglob
-trap "clean 126" SIGINT # Ensure cleanup on ^C
+trap "clean 128" SIGINT # Ensure cleanup on ^C
 check_deps() {
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        [[ -n $(command -v "$d") ]] || errx 127 "$d is not installed"
     done; unset d
 }
 check_lock() {
-    [[ -n $cache ]] || errx 125 "Cache is not defined"
+    [[ -n $cache ]] || errx 126 "Cache is not defined"
     mkdir -p "$cache"
-    if [[ -f "$cache/.lock" ]]; then
-        errx 124 "$cache/.lock already exists"
+    if [[ -f "$cache.lock" ]]; then
+        errx 125 "$cache.lock already exists"
     fi
-    echo "$$" >"$cache/.lock"
+    echo "$$" >"$cache.lock"
 }
 check_resume_file() {
     if [[ -f "$json" ]] && [[ -z $resume ]]; then
@@ -33,10 +33,10 @@ check_resume_file() {
                 *) echo "Invalid response, try again!" ;;
             esac
         done
-    elif [[ -f $json ]]; then
+    elif [[ -f "$json" ]]; then
         read_resume_file
     elif [[ -n $resume ]]; then
-        errx 123 "No resume file found"
+        errx 124 "No resume file found"
     else
         write_resume_file
     fi
@@ -46,8 +46,8 @@ clean() {
         [[ -z $cache ]] || [[ ! -d "$cache" ]] || rm -rf "$cache"
     fi
     [[ -z $script ]] || [[ ! -f "$script" ]] || rm -f "$script"
+    [[ ${1:-0} -eq 125 ]] || [[ -z $cache ]] || rm -f "$cache.lock"
     show_cursor
-    [[ ${1:-0} -eq 125 ]] || [[ -z $cache ]] || rm -f "$cache/.lock"
     exit "${1:-0}"
 }
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
@@ -56,13 +56,16 @@ good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
 hide_cursor() { echo -en "\e[?25l"; }
 info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 json_get() {
-    [[ -z $json ]] || jq -cr ".$*" "$json" | sed -r "s/^null$//g"
+    if [[ -z $json ]] || [[ ! -f "$json" ]]; then
+        return
+    fi
+    jq -cr ".$*" "$json" | sed -r "s/^null$//g"
 }
 long_opt() {
     local arg shift="0"
     case "$1" in
-        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
-        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 123 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 123; arg="$1" ;;
     esac
     echo "$arg"
     return $shift
@@ -97,8 +100,11 @@ EOF
 }
 
 write_resume_file() {
-    [[ -z $cache ]] || rm -rf "$cache"
+    [[ -n $cache ]] || return
+    [[ -n $json ]] || return
+    rm -rf "$cache"
     mkdir -p "$cache"
+
     # TODO
     cat >"$json" <<EOF
 {
@@ -157,12 +163,12 @@ cache="$HOME/.cache/${0##*/}/$hash"
 joblog="$cache/joblog.txt"
 json="$cache/${0##*/}.json"
 
+# Lock to prevent parallel issues
+check_lock
+
 # Check for resume file
 [[ -z $parallel ]] || check_resume_file
 hide_cursor
-
-# Lock to prevent parallel issues
-check_lock
 
 [[ -z $resume ]] || info "Resuming..."
 
