Much better bash_parallel, resume support

diff --git a/bash_parallel b/bash_parallel
--- a/bash_parallel
+++ b/bash_parallel
@@ -1,6 +1,10 @@
 #!/usr/bin/env bash
 
-clean() { [[ -z $script ]] || rm -f $script; exit $1; }
+clean() {
+    [[ ${1:-0} -ne 0 ]] || [[ ! -d $cache ]] || rm -rf $cache
+    [[ -z $script ]] || [[ ! -f $script ]] || rm -f $script
+    exit ${1:-0}
+}
 
 err() { echo -e "${color:+\e[31m}[!] $@\e[0m"; }
 
@@ -20,8 +24,13 @@ long_opt() {
     return $shift
 }
 
+# TODO
+read_resume_file() { echo -n; }
+
+subinfo() { echo -e "${color:+\e[36m}[=] $@\e[0m"; }
+
 usage() {
-    echo "Usage: ${0/*\//} [OPTIONS] <arg1>... [argN]"
+    echo "Usage: ${0##*/} [OPTIONS] <arg1>... [argN]"
     echo
     echo "TODO"
     echo
@@ -29,20 +38,30 @@ usage() {
     echo "    -f, --flag           Example flag"
     echo "    -h, --help           Display this help message"
     echo "    --nocolor            Disable colorized output"
+    echo "    -r, --resume         Resume from a previous run"
     echo "    -s, --store=VAL      Example for storing cli arg"
-    local default="(default: $threads)"
     echo "    -t, --threads=NUM    Use the specied number of threads"
-    echo "                         if running in parallel $default"
+    echo "                         (default: $threads)"
+    echo "    -v, --verobse        Do not hide parallel errors"
     echo
     exit $1
 }
 
 warn() { echo -e "${color:+\e[33m}[-] $@\e[0m"; }
 
+# TODO
+write_resume_file() {
+    cat >$json <<EOF
+EOF
+}
+
 declare -a args
 unset flag help store
+cache="${0##*/}.resume"
 color="true"
 parallel="true"
+joblog="$cache/joblog.txt"
+json="$cache/${0##*/}.json"
 threads="32"
 
 # Parse command line options
@@ -52,8 +71,10 @@ while [[ $# -gt 0 ]]; do
         "-f"|"--flag") flag="true" ;;
         "-h"|"--help") help="true" ;;
         "--nocolor") unset color ;;
+        "-r"|"--resume") resume="--resume" ;;
         "-s"|"--store"*) store="$(long_opt $@)" || shift ;;
         "-t"|"--threads"*) threads="$(long_opt $@)" || shift ;;
+        "-v"|"--verbose") verbose="true" ;;
         *) args+=("$1") ;;
     esac
     shift
@@ -62,10 +83,10 @@ done
 
 # Check for valid params and missing dependencies
 [[ -z $help ]] || usage 0
-[[ $# -gt 0 ]] || usage 2
-for dep in TODO; do
-    [[ -n $(command -v $dep) ]] || errx 3 "$dep is not installed"
-done; unset dep
+[[ $# -gt 0 ]] || [[ -n $resume ]] || usage 2
+# for dep in TODO; do
+#     [[ -n $(command -v $dep) ]] || errx 3 "$dep is not installed"
+# done; unset dep
 
 # Determine parallel situation
 if [[ -n $parallel ]] && [[ -z $(command -v parallel) ]]; then
@@ -79,12 +100,64 @@ if [[ -n $parallel ]] && [[ ! -f $HOME/.parallel/will-cite ]]; then
     parallel --citation
 fi
 
-# Script used by parallel
-script="/tmp/${0/*\//}.parallel"
-trap clean SIGINT
+if [[ -n $parallel ]]; then
+    # Ensure resume directory exists
+    mkdir -p $cache
 
+    # Check for resume file
+    if [[ -f $json ]] && [[ -z $resume ]]; then
+        warn "Resume file found" >&2
+        while :; do
+            # Prompt whether to overwrite or resume
+            read -n 1 -p "Would you like to resume [y/n/q]: " -s ans
+            echo
+
+            case "$ans" in
+                "n") write_resume_file; break ;;
+                "q") exit 0 ;;
+                "y") read_resume_file; resume="--resume"; break ;;
+                *) echo "Invalid response, try again!" ;;
+            esac
+        done
+    elif [[ -f $json ]]; then
+        read_resume_file
+    elif [[ -n $resume ]]; then
+        errx 6 "No resume file found in current directory"
+    else
+        write_resume_file
+    fi
+fi
+
+# Dataset used by parallel
+dataset="$cache/${0##*/}.dataset"
+
+# Script used by parallel
+script="/tmp/${0##*/}.parallel"
+
+# Ensure cleanup on ^C
+trap "clean -1" SIGINT
+
+# Process dataset
+info "Processing dataset for jobs"
+
+if [[ ! -f $dataset ]]; then
+    total="0"
+    for data in "$@"; do
+        ((total += 1))
+        echo "$data" >>$dataset
+    done; unset data
+else
+    total="$(cat $dataset | wc -l)"
+fi
+[[ $total -ne 0 ]] || errx 4 "No dataset provided"
+
+info "$total jobs to run"
+
+# Create sub-script
 cat >$script <<EOF
 #!/usr/bin/env bash
+
+set -o noglob
 
 err() { echo -e "\r${color:+\e[31m}[!] \$@\e[0m\e[K"; }
 
@@ -94,58 +167,31 @@ good() { echo -e "\r${color:+\e[32m}[+] \$@\e[0m\e[K"; }
 
 info() { echo -e "\r${color:+\e[37m}[*] \$@\e[0m\e[K"; }
 
+subinfo() { echo -e "\r${color:+\e[36m}[=] \$@\e[0m\e[K"; }
+
 warn() { echo -e "\r${color:+\e[33m}[-] \$@\e[0m\e[K"; }
 
-let "timeout = RANDOM % 5"
-sleep \$timeout && good "\$1" # TODO
+# TODO
+let "timeout = RANDOM % 4"
+sleep \$timeout
+good "\$1"
 EOF
 chmod 700 $script
 
-info "Processing dataset for jobs"
-
-declare -a dataset=($@)
-let "total = ${#dataset[@]}"
-
-[[ $total -ne 0 ]] || errx 4 "No dataset provided"
-
-info "$total jobs to run"
+# Run sub-script
 if [[ -n $parallel ]]; then
-    # Math
-    left="$total"
-    marker="0"
-    maxdata="$(
-        parallel -r --show-limit </dev/null | \
-        awk '/Maximal used/ {print $NF; exit}'
-    )"
-    let "remainder = total % maxdata"
-    round="0"
-    let "rounds = total / maxdata"
-    [[ $remainder -eq 0 ]] || let "rounds += 1"
-
-    # Loop thru rounds
-    [[ $rounds -eq 1 ]] || info "Splitting into $rounds rounds"
-    while [[ $left -gt 0 ]]; do
-        let "round += 1"
-        [[ $rounds -eq 1 ]] || warn "Round $round"
-
-        increment="$left"
-        [[ $left -le $maxdata ]] || increment="$maxdata"
-
-        parallel --bar --lb -P $threads -r $script {} ::: \
-            ${dataset[@]:$marker:$increment}
-
-        let "left -= increment"
-        let "marker += increment"
-        echo -en "\e[1A\e[K"
-    done
+    # If more than one dataset, cat and pipe to parallel
+    parallel -a $dataset --bar --joblog ${resume:++}$joblog --lb \
+        -P $threads -r $resume $script {}
+    [[ -n $verbose ]] || echo -en "\e[1A\e[K" >&2
 else
-    let "count = 1"
-    for data in "${dataset[@]}"; do
+    count="1"
+    while read -r data; do
         echo -e "\r\e[K" >&2
         echo -en "${color:+\e[37m}[$count/$total]\e[0m\e[K\e[1A" >&2
         $script "$data"
         let "count += 1"
-    done; unset data
+    done <$dataset; unset data
 fi
 
 clean
