Updated bash and bash_parallel

diff --git a/bash_parallel b/bash_parallel
--- a/bash_parallel
+++ b/bash_parallel
@@ -2,18 +2,44 @@
 
 ### Helpers begin
 set -o noglob
-check_and_lock() {
-    [[ -n $cache ]] || errx 124 "Cache is not defined"
-    mkdir -p "$cache"
-    if [[ -f "$cache/.lock" ]]; then
-        errx 125 "$cache/.lock already exists"
-    fi
-    echo "$$" >"$cache/.lock"
-}
-checkdeps() {
+trap "clean 126" SIGINT # Ensure cleanup on ^C
+check_deps() {
     for d in "${deps[@]}"; do
         [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
     done; unset d
+}
+check_lock() {
+    [[ -n $cache ]] || errx 125 "Cache is not defined"
+    mkdir -p "$cache"
+    if [[ -f "$cache/.lock" ]]; then
+        errx 124 "$cache/.lock already exists"
+    fi
+    echo "$$" >"$cache/.lock"
+}
+check_resume_file() {
+    if [[ -f "$json" ]] && [[ -z $resume ]]; then
+        warn "Resume file found" >&2
+        while :; do
+            # Prompt whether to overwrite or resume
+            local a
+            read -n 1 -p "Would you like to resume [y/n/q/c]: " -rs a
+            echo
+
+            case "$a" in
+                "c") clean 0 ;;
+                "n") write_resume_file; break ;;
+                "q") exit 0 ;;
+                "y") read_resume_file; resume="--resume"; break ;;
+                *) echo "Invalid response, try again!" ;;
+            esac
+        done
+    elif [[ -f $json ]]; then
+        read_resume_file
+    elif [[ -n $resume ]]; then
+        errx 123 "No resume file found in current directory"
+    else
+        write_resume_file
+    fi
 }
 clean() {
     if [[ ${1:-0} -eq 0 ]]; then
@@ -27,6 +53,7 @@ clean() {
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
 errx() { echo -e "${color:+\e[31m}[!] ${*:2}\e[0m"; clean "$1"; }
 good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+hide_cursor() { echo -en "\e[?25l"; }
 info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 json_get() {
     [[ -z $json ]] || jq -cr ".$*" "$json" | sed -r "s/^null$//g"
@@ -88,7 +115,7 @@ parallel="true"
 threads="32"
 
 # Check for missing dependencies
-checkdeps
+check_deps
 
 # Parse command line options
 while [[ $# -gt 0 ]]; do
@@ -111,14 +138,6 @@ done
 [[ -z $help ]] || usage 0
 [[ $# -gt 0 ]] || [[ -n $resume ]] || usage 1
 
-# Cache variables
-cache="$HOME/.cache/${0##*/}/$(pwd | sha256sum | awk '{print $1}')"
-joblog="$cache/joblog.txt"
-json="$cache/${0##*/}.json"
-
-# Lock to prevent parallel issues
-check_and_lock
-
 # Determine parallel situation
 if [[ -n $parallel ]] && [[ -z $(command -v parallel) ]]; then
     warn "Parallel is not installed, defaulting to single-threaded"
@@ -131,47 +150,24 @@ if [[ -n $parallel ]] && [[ ! -f "$HOME/.parallel/will-cite" ]]; then
     parallel --citation
 fi
 
+# Cache variables
+hash="$(pwd | sha256sum | awk '{print $1}')"
+cache="$HOME/.cache/${0##*/}/$hash"
+joblog="$cache/joblog.txt"
+json="$cache/${0##*/}.json"
+
 # Check for resume file
-if [[ -z $parallel ]]; then
-    echo -n # do nothing
-elif [[ -f "$json" ]] && [[ -z $resume ]]; then
-    warn "Resume file found" >&2
-    while :; do
-        # Prompt whether to overwrite or resume
-        read -n 1 -p "Would you like to resume [y/n/q/c]: " -rs ans
-        echo
+[[ -z $parallel ]] || check_resume_file
+hide_cursor
 
-        case "$ans" in
-            "c") clean 0 ;;
-            "n") write_resume_file; break ;;
-            "q") exit 0 ;;
-            "y") read_resume_file; resume="--resume"; break ;;
-            *) echo "Invalid response, try again!" ;;
-        esac
-    done
-elif [[ -f $json ]]; then
-    read_resume_file
-elif [[ -n $resume ]]; then
-    errx 2 "No resume file found in current directory"
-else
-    write_resume_file
-fi
+# Lock to prevent parallel issues
+check_lock
 
-# Dataset used by parallel
-dataset="$cache/${0##*/}.dataset"
+[[ -z $resume ]] || info "Resuming..."
 
-# Script used by parallel
-script="/tmp/${0##*/}.parallel"
-
-# Ensure cleanup on ^C
-trap "clean 126" SIGINT
-
-# Hide cursor
-echo -en "\e[?25l"
-
-# Process dataset
 info "Processing dataset for jobs"
 
+dataset="$cache/${0##*/}.dataset"
 if [[ ! -f "$dataset" ]]; then
     total="0"
     for data in "$@"; do
@@ -181,11 +177,12 @@ if [[ ! -f "$dataset" ]]; then
 else
     total="$(wc -l "$dataset" | awk '{print $1}')"
 fi
-[[ $total -gt 0 ]] || errx 0 "No dataset provided"
+[[ $total -gt 0 ]] || errx 2 "No dataset provided"
 
 subinfo "$total jobs to run"
 
 # Create sub-script
+script="/tmp/${0##*/}.parallel"
 cat >"$script" <<EOF
 #!/usr/bin/env bash
 
